In [3]:
import numpy as np
a = np.array ([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
mean_a = np.mean(a, axis = 0)
mean_a

array([2. , 8.4])

In [15]:
a_centered = a - mean_a
a_centered


array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [11]:
a1=a_centered[:,0]
a2=a_centered[:,1]
a_centered_sp=np.dot(a1,a2)
N=a.shape[0]
result = a_centered_sp/ (N-1)
result

2.0

In [13]:
arr_covar = np.cov(np.transpose(a))
arr_covar

array([[1. , 2. ],
       [2. , 4.3]])

In [14]:
number_covar = arr_covar[0,1]
number_covar

2.0